const country = [
    ['AX', 'Islas Aland'],
    ['AL', 'Albania'],
    ['DZ', 'Argelia'],
    ['AS', 'Samoa Americana'],
    ['AD', 'Andorra'],
    ['AO', 'Angola'],
    ['AI', 'Anguila'],
    ['AG', 'Antigua y Barbuda'],
    ['AR', 'Argentina'],
    ['AM', 'Armenia'],
    ['AW', 'Aruba'],
    ['AU', 'Australia'],
    ['AT', 'Austria'],
    ['AZ', 'Azerbaiyán'],
    ['BS', 'Bahamas'],
    ['BH', 'Baréin'],
    ['BD', 'Bangladesh'],
    ['BB', 'Barbados'],
    ['BY', 'Bielorrusia'],
    ['BE', 'Bélgica'],
    ['BZ', 'Belice'],
    ['BJ', 'Benín'],
    ['BM', 'Bermudas'],
    ['BT', 'Bután'],
    ['BO', 'Bolivia'],
    ['BQ', 'Bonaire, San Eustaquio y Saba'],
    ['BA', 'Bosnia y Herzegovina'],
    ['BW', 'Botsuana'],
    ['BR', 'Brasil'],
    ['BN', 'Brunéi Darussalam'],
    ['BG', 'Bulgaria'],
    ['BF', 'Burkina Faso'],
    ['BI', 'Burundi'],
    ['KH', 'Camboya'],
    ['CM', 'Camerún'],
    ['CA', 'Canadá'],
    ['IC', 'Islas Canarias, España'],
    ['CV', 'Cabo Verde'],
    ['KY', 'Islas Caimán'],
    ['CF', 'República Centroafricana'],
    ['TD', 'Chad'],
    ['CL', 'Chile'],
    ['CN', 'China, República Popular de'],
    ['CO', 'Colombia'],
    ['KM', 'Comoras'],
    ['CG', 'Congo'],
    ['CK', 'Islas Cook'],
    ['CR', 'Costa Rica'],
    ['HR', 'Croacia'],
    ['CW', 'Curazao'],
    ['CY', 'Chipre'],
    ['CZ', 'República Checa'],
    ['DK', 'Dinamarca'],
    ['DJ', 'Yibuti'],
    ['DM', 'Dominica'],
    ['DO', 'República Dominicana'],
    ['EC', 'Ecuador'],
    ['EG', 'Egipto'],
    ['SV', 'El Salvador'],
    ['GQ', 'Guinea Ecuatorial'],
    ['ER', 'Eritrea'],
    ['EE', 'Estonia'],
    ['ET', 'Etiopía'],
    ['FK', 'Islas Malvinas (Falkland)'],
    ['FO', 'Islas Feroe (Dinamarca)'],
    ['FJ', 'Fiyi'],
    ['FI', 'Finlandia'],
    ['FR', 'Francia'],
    ['GF', 'Guayana Francesa'],
    ['PF', 'Polinesia Francesa (Tahití)'],
    ['TF', 'Territorios Australes Franceses'],
    ['GA', 'Gabón'],
    ['GM', 'Gambia'],
    ['GE', 'Georgia'],
    ['DE', 'Alemania'],
    ['GH', 'Ghana'],
    ['GI', 'Gibraltar'],
    ['GR', 'Grecia'],
    ['GL', 'Groenlandia (Dinamarca)'],
    ['GD', 'Granada'],
    ['GP', 'Guadalupe'],
    ['GU', 'Guam'],
    ['GT', 'Guatemala'],
    ['GG', 'Guernsey'],
    ['GN', 'Guinea'],
    ['GW', 'Guinea-Bissau'],
    ['GY', 'Guyana'],
    ['HT', 'Haití'],
    ['HM', 'Islas Heard y McDonald'],
    ['HN', 'Honduras'],
    ['HK', 'Hong Kong'],
    ['HU', 'Hungría'],
    ['IS', 'Islandia'],
    ['IN', 'India'],
    ['ID', 'Indonesia'],
    ['IQ', 'Irak'],
    ['IE', 'Irlanda'],
    ['IM', 'Isla de Man'],
    ['IL', 'Israel'],
    ['IT', 'Italia'],
    ['CI', 'Costa de Marfil'],
    ['JM', 'Jamaica'],
    ['JP', 'Japón'],
    ['JE', 'Jersey'],
    ['JO', 'Jordania'],
    ['KZ', 'Kazajistán'],
    ['KE', 'Kenia'],
    ['KI', 'Kiribati'],
    ['KR', 'Corea, República de'],
    ['KW', 'Kuwait'],
    ['KG', 'Kirguistán'],
    ['LA', 'Laos'],
    ['LV', 'Letonia'],
    ['LB', 'Líbano'],
    ['LS', 'Lesoto'],
    ['LR', 'Liberia'],
    ['LI', 'Liechtenstein'],
    ['LT', 'Lituania'],
    ['LU', 'Luxemburgo'],
    ['MO', 'Macao'],
    ['MK', 'Macedonia'],
    ['MG', 'Madagascar'],
    ['MW', 'Malaui'],
    ['MY', 'Malasia'],
    ['MV', 'Maldivas'],
    ['ML', 'Malí'],
    ['MT', 'Malta'],
    ['MH', 'Islas Marshall'],
    ['MQ', 'Martinica'],
    ['MR', 'Mauritania'],
    ['MU', 'Mauricio'],
    ['YT', 'Mayotte'],
    ['MX', 'México'],
    ['FM', 'Micronesia, Estados Federados de'],
    ['MD', 'Moldavia'],
    ['MC', 'Mónaco'],
    ['MN', 'Mongolia'],
    ['ME', 'Montenegro'],
    ['MS', 'Montserrat'],
    ['MA', 'Marruecos'],
    ['MZ', 'Mozambique'],
    ['MM', 'Myanmar'],
    ['NA', 'Namibia'],
    ['NR', 'Nauru, República de'],
    ['NP', 'Nepal'],
    ['NL', 'Países Bajos'],
    ['NC', 'Nueva Caledonia'],
    ['NZ', 'Nueva Zelanda'],
    ['NI', 'Nicaragua'],
    ['NE', 'Níger'],
    ['NG', 'Nigeria'],
    ['NU', 'Isla Niue'],
    ['NF', 'Isla Norfolk'],
    ['MP', 'Islas Marianas del Norte'],
    ['NO', 'Noruega'],
    ['OM', 'Omán'],
    ['PK', 'Pakistán'],
    ['PW', 'Palaos'],
    ['PS', 'Palestina'],
    ['PA', 'Panamá'],
    ['PG', 'Papúa Nueva Guinea'],
    ['PY', 'Paraguay'],
    ['PE', 'Perú'],
    ['PH', 'Filipinas'],
    ['PN', 'Pitcairn'],
    ['PL', 'Polonia'],
    ['PT', 'Portugal'],
    ['PR', 'Puerto Rico'],
    ['QA', 'Catar'],
    ['RE', 'Reunión'],
    ['RO', 'Rumania'],
    ['RU', 'Rusia'],
    ['RW', 'Ruanda'],
    ['SH', 'Santa Elena'],
    ['PM', 'San Pedro y Miquelón'],
    ['WS', 'Samoa'],
    ['SM', 'San Marino'],
    ['ST', 'Santo Tomé y Príncipe'],
    ['SA', 'Arabia Saudita'],
    ['SN', 'Senegal'],
    ['RS', 'Serbia'],
    ['SC', 'Seychelles'],
    ['SL', 'Sierra Leona'],
    ['SG', 'Singapur'],
    ['SK', 'Eslovaquia'],
    ['SI', 'Eslovenia'],
    ['SB', 'Islas Salomón'],
    ['ZA', 'Sudáfrica'],
    ['SS', 'Sudán del Sur'],
    ['ES', 'España'],
    ['LK', 'Sri Lanka'],
    ['BL', 'San Bartolomé'],
    ['KN', 'San Cristóbal y Nieves'],
    ['LC', 'Santa Lucía'],
    ['MF', 'San Martín'],
    ['VC', 'San Vicente'],
    ['SD', 'Sudán'],
    ['SR', 'Surinam'],
    ['SJ', 'Svaldbard'],
    ['SZ', 'Suazilandia'],
    ['SE', 'Suecia'],
    ['CH', 'Suiza'],
    ['TW', 'Taiwán'],
    ['TJ', 'Tayikistán'],
    ['TZ', 'Tanzania'],
    ['TH', 'Tailandia'],
    ['TL', 'Timor-Leste'],
    ['TG', 'Togo'],
    ['TK', 'Tokelau'],
    ['TO', 'Tonga'],
    ['TT', 'Trinidad y Tobago'],
    ['TN', 'Túnez'],
    ['TR', 'Turquía'],
    ['TM', 'Turkmenistán'],
    ['TC', 'Islas Turcas y Caicos'],
    ['TV', 'Tuvalu'],
    ['UG', 'Uganda'],
    ['UA', 'Ucrania'],
    ['AE', 'Emiratos Árabes Unidos'],
    ['GB', 'Reino Unido'],
    ['US', 'Estados Unidos'],
    ['UM', 'Islas Ultramarinas Menores de Estados Unidos'],
    ['UY', 'Uruguay'],
    ['UZ', 'Uzbekistán'],
    ['VU', 'Vanuatu'],
    ['VA', 'Ciudad del Vaticano'],
    ['VE', 'Venezuela'],
    ['VN', 'Vietnam'],
    ['VG', 'Islas Vírgenes (Británicas)'],
    ['VI', 'Islas Vírgenes (EE.UU.)'],
    ['WF', 'Wallis y Futuna'],
    ['EH', 'Sahara Occidental'],
    ['YE', 'Yemen'],
    ['ZM', 'Zambia'],
    ['ZW', 'Zimbabue'],
]

export default country;
