const country = [
    ['AL',	'Albania'],
    ['DE',	'Alemania'],
    ['AD',	'Andorra'],
    ['AO',	'Angola'],
    ['AI',	'Anguila'],
    ['AG',	'Antigua y Barbuda'],
    ['SA',	'Arabia Saudita'],
    ['DZ',	'Argelia'],
    ['AR',	'Argentina'],
    ['AM',	'Armenia'],
    ['AW',	'Aruba'],
    ['AU',	'Australia'],
    ['AT',	'Austria'],
    ['AZ',	'Azerbaiyán'],
    ['BS',	'Bahamas'],
    ['BD',	'Bangladesh'],
    ['BB',	'Barbados'],
    ['BH',	'Baréin'],
    ['BE',	'Bélgica'],
    ['BZ',	'Belice'],
    ['BJ',	'Benín'],
    ['BM',	'Bermudas'],
    ['BY',	'Bielorrusia'],
    ['BO',	'Bolivia'],
    ['BQ',	'Bonaire, San Eustaquio y Saba'],
    ['BA',	'Bosnia y Herzegovina'],
    ['BW',	'Botsuana'],
    ['BR',	'Brasil'],
    ['BN',	'Brunéi Darussalam'],
    ['BG',	'Bulgaria'],
    ['BF',	'Burkina Faso'],
    ['BI',	'Burundi'],
    ['BT',	'Bután'],
    ['CV',	'Cabo Verde'],
    ['KH',	'Camboya'],
    ['CM',	'Camerún'],
    ['CA',	'Canadá'],
    ['QA',	'Catar'],
    ['TD',	'Chad'],
    ['CL',	'Chile'],
    ['CN',	'China, República Popular de'],
    ['CY',	'Chipre'],
    ['VA',	'Ciudad del Vaticano'],
    ['CO',	'Colombia'],
    ['KM',	'Comoras'],
    ['CG',	'Congo'],
    ['KR',	'Corea, República de'],
    ['CI',	'Costa de Marfil'],
    ['CR',	'Costa Rica'],
    ['HR',	'Croacia'],
    ['CW',	'Curazao'],
    ['DK',	'Dinamarca'],
    ['DM',	'Dominica'],
    ['EC',	'Ecuador'],
    ['EG',	'Egipto'],
    ['SV',	'El Salvador'],
    ['AE',	'Emiratos Árabes Unidos'],
    ['ER',	'Eritrea'],
    ['SK',	'Eslovaquia'],
    ['SI',	'Eslovenia'],
    ['ES',	'España'],
    ['US',	'Estados Unidos'],
    ['EE',	'Estonia'],
    ['ET',	'Etiopía'],
    ['PH',	'Filipinas'],
    ['FI',	'Finlandia'],
    ['FJ',	'Fiyi'],
    ['FR',	'Francia'],
    ['GA',	'Gabón'],
    ['GM',	'Gambia'],
    ['GE',	'Georgia'],
    ['GH',	'Ghana'],
    ['GI',	'Gibraltar'],
    ['GD',	'Granada'],
    ['GR',	'Grecia'],
    ['GL',	'Groenlandia (Dinamarca)'],
    ['GP',	'Guadalupe'],
    ['GU',	'Guam'],
    ['GT',	'Guatemala'],
    ['GF',	'Guayana Francesa'],
    ['GG',	'Guernsey'],
    ['GQ',	'Guinea Ecuatorial'],
    ['GN',	'Guinea'],
    ['GW',	'Guinea-Bissau'],
    ['GY',	'Guyana'],
    ['HT',	'Haití'],
    ['HN',	'Honduras'],
    ['HK',	'Hong Kong'],
    ['HU',	'Hungría'],
    ['IN',	'India'],
    ['ID',	'Indonesia'],
    ['IQ',	'Irak'],
    ['IE',	'Irlanda'],
    ['IM',	'Isla de Man'],
    ['NU',	'Isla Niue'],
    ['NF',	'Isla Norfolk'],
    ['IS',	'Islandia'],
    ['AX',	'Islas Aland'],
    ['KY',	'Islas Caimán'],
    ['IC',	'Islas Canarias, España'],
    ['CK',	'Islas Cook'],
    ['FO',	'Islas Feroe (Dinamarca)'],
    ['HM',	'Islas Heard y McDonald'],
    ['FK',	'Islas Malvinas (Falkland)'],
    ['MP',	'Islas Marianas del Norte'],
    ['MH',	'Islas Marshall'],
    ['SB',	'Islas Salomón'],
    ['TC',	'Islas Turcas y Caicos'],
    ['UM',	'Islas Ultramarinas Menores de Estados Unidos'],
    ['VG',	'Islas Vírgenes (Británicas)'],
    ['VI',	'Islas Vírgenes (EE.UU.)'],
    ['IL',	'Israel'],
    ['IT',	'Italia'],
    ['JM',	'Jamaica'],
    ['JP',	'Japón'],
    ['JE',	'Jersey'],
    ['JO',	'Jordania'],
    ['KZ',	'Kazajistán'],
    ['KE',	'Kenia'],
    ['KG',	'Kirguistán'],
    ['KI',	'Kiribati'],
    ['KW',	'Kuwait'],
    ['LA',	'Laos'],
    ['LS',	'Lesoto'],
    ['LV',	'Letonia'],
    ['LB',	'Líbano'],
    ['LR',	'Liberia'],
    ['LI',	'Liechtenstein'],
    ['LT',	'Lituania'],
    ['LU',	'Luxemburgo'],
    ['MO',	'Macao'],
    ['MK',	'Macedonia'],
    ['MG',	'Madagascar'],
    ['MY',	'Malasia'],
    ['MW',	'Malaui'],
    ['MV',	'Maldivas'],
    ['ML',	'Malí'],
    ['MT',	'Malta'],
    ['MA',	'Marruecos'],
    ['MQ',	'Martinica'],
    ['MU',	'Mauricio'],
    ['MR',	'Mauritania'],
    ['YT',	'Mayotte'],
    ['MX',	'México'],
    ['FM',	'Micronesia, Estados Federados de'],
    ['MD',	'Moldavia'],
    ['MC',	'Mónaco'],
    ['MN',	'Mongolia'],
    ['ME',	'Montenegro'],
    ['MS',	'Montserrat'],
    ['MZ',	'Mozambique'],
    ['MM',	'Myanmar'],
    ['NA',	'Namibia'],
    ['NR',	'Nauru, República de'],
    ['NP',	'Nepal'],
    ['NI',	'Nicaragua'],
    ['NE',	'Níger'],
    ['NG',	'Nigeria'],
    ['NO',	'Noruega'],
    ['NC',	'Nueva Caledonia'],
    ['NZ',	'Nueva Zelanda'],
    ['OM',	'Omán'],
    ['NL',	'Países Bajos'],
    ['PK',	'Pakistán'],
    ['PW',	'Palaos'],
    ['PS',	'Palestina'],
    ['PA',	'Panamá'],
    ['PG',	'Papúa Nueva Guinea'],
    ['PY',	'Paraguay'],
    ['PE',	'Perú'],
    ['PN',	'Pitcairn'],
    ['PF',	'Polinesia Francesa (Tahití)'],
    ['PL',	'Polonia'],
    ['PT',	'Portugal'],
    ['PR',	'Puerto Rico'],
    ['GB',	'Reino Unido'],
    ['CF',	'República Centroafricana'],
    ['CZ',	'República Checa'],
    ['DO',	'República Dominicana'],
    ['RE',	'Reunión'],
    ['RW',	'Ruanda'],
    ['RO',	'Rumania'],
    ['RU',	'Rusia'],
    ['EH',	'Sahara Occidental'],
    ['AS',	'Samoa Americana'],
    ['WS',	'Samoa'],
    ['BL',	'San Bartolomé'],
    ['KN',	'San Cristóbal y Nieves'],
    ['SM',	'San Marino'],
    ['MF',	'San Martín'],
    ['PM',	'San Pedro y Miquelón'],
    ['VC',	'San Vicente'],
    ['SH',	'Santa Elena'],
    ['LC',	'Santa Lucía'],
    ['ST',	'Santo Tomé y Príncipe'],
    ['SN',	'Senegal'],
    ['RS',	'Serbia'],
    ['SC',	'Seychelles'],
    ['SL',	'Sierra Leona'],
    ['SG',	'Singapur'],
    ['LK',	'Sri Lanka'],
    ['SZ',	'Suazilandia'],
    ['ZA',	'Sudáfrica'],
    ['SS',	'Sudán del Sur'],
    ['SD',	'Sudán'],
    ['SE',	'Suecia'],
    ['CH',	'Suiza'],
    ['SR',	'Surinam'],
    ['SJ',	'Svaldbard'],
    ['TH',	'Tailandia'],
    ['TW',	'Taiwán'],
    ['TZ',	'Tanzania'],
    ['TJ',	'Tayikistán'],
    ['TF',	'Territorios Australes Franceses'],
    ['TL',	'Timor-Leste'],
    ['TG',	'Togo'],
    ['TK',	'Tokelau'],
    ['TO',	'Tonga'],
    ['TT',	'Trinidad y Tobago'],
    ['TN',	'Túnez'],
    ['TM',	'Turkmenistán'],
    ['TR',	'Turquía'],
    ['TV',	'Tuvalu'],
    ['UA',	'Ucrania'],
    ['UG',	'Uganda'],
    ['UY',	'Uruguay'],
    ['UZ',	'Uzbekistán'],
    ['VU',	'Vanuatu'],
    ['VE',	'Venezuela'],
    ['VN',	'Vietnam'],
    ['WF',	'Wallis y Futuna'],
    ['YE',	'Yemen'],
    ['DJ',	'Yibuti'],
    ['ZM',	'Zambia'],
    ['ZW',	'Zimbabue'],
]

export default country;
